# docker-compose up -d && docker exec -it pizzeriaviasoft_app bash
version: "3"

services:
  node:
    image: node:18-alpine
    container_name: pizzeriaviasoft_app
    build: ./ 
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - 3002:3002
    environment:
      - MONGO_URI=mongodb://mongodb:27017/viasoft_db_server

  mongodb:
    image: mongo:5.0.7
    container_name: viasoft_db
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27018:27017

networks:
  default:
    name: viasoft_net

