# docker-compose up -d && docker exec -it pizzeriaviasoft_app bash
version: "3.8"

services:
  app:
    image: node:18-alpine
    container_name: pizzeriaviasoft_app
    build: .
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres_user:postgres_password@postgres:5432/postgres_db?schema=public

  postgres:
    image: postgres:14
    container_name: pizzeriaviasoft_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    name: pizzeriaviasoft_postgres_data

networks:
  default:
    name: viasoft_net
